# Generated by Django 5.1 on 2024-12-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0003_descargadocumento_delete_documentodescargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargafamiliar',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='cargas_familiares/'),
        ),
        migrations.AddField(
            model_name='cargafamiliar',
            name='tipo_certificado',
            field=models.CharField(blank=True, choices=[('AFC', 'Certificado de Carga Familiar (AFC)'), ('ISAPRE', 'Certificado de Carga Familiar de la Isapre'), ('SUBSIDIOS', 'Certificado de Carga Familiar para Subsidios o Beneficios Sociales'), ('SII', 'Certificado de Carga Familiar del Servicio de Impuestos Internos (SII)'), ('REGISTRO_CIVIL', 'Certificados del Registro Civil'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
    ]
