# Generated by Django 5.1.3 on 2024-12-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0004_cargafamiliar_archivo_cargafamiliar_tipo_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10, null=True),
        ),
    ]
