# Generated by Django 5.1.3 on 2024-12-03 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0006_customuser_alergia_medicamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='alergia_medicamento',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='contrato_adjunto',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='enfermedades',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='primer_nombre',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='segundo_nombre',
        ),
    ]
