# Generated by Django 5.1 on 2024-12-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0007_remove_customuser_alergia_medicamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
