# Generated by Django 5.1 on 2024-12-06 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0009_customuser_certificado_afp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='participantes',
        ),
        migrations.CreateModel(
            name='ProgresoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso', models.PositiveIntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='gestiones.curso')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
