# Generated by Django 5.1 on 2024-12-06 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0010_remove_curso_participantes_progresoparticipante'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='cursos', to=settings.AUTH_USER_MODEL),
        ),
    ]
