# Generated by Django 5.1 on 2024-12-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0011_curso_participantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='curso',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Modulo',
        ),
    ]
