# Generated by Django 5.1 on 2024-12-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0012_remove_modulo_curso_delete_comentario_delete_modulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialdenuncia',
            name='denuncia',
        ),
        migrations.RemoveField(
            model_name='historialdenuncia',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ContactoEmergencia',
        ),
        migrations.DeleteModel(
            name='HistorialDenuncia',
        ),
    ]
