# Generated by Django 5.1 on 2024-10-17 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0018_publicacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacion',
            name='año',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2025)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='mes',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=1),
            preserve_default=False,
        ),
    ]
