# Generated by Django 5.1 on 2024-11-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0020_documentoempresa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Liquidacion',
        ),
    ]
