# Generated by Django 5.1 on 2024-11-26 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0021_delete_liquidacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dias_vacaciones_disponibles',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='SolicitudVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=50)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_vacaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
