# Generated by Django 5.1 on 2024-11-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0022_customuser_dias_vacaciones_disponibles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dias_vacaciones_disponibles',
        ),
        migrations.DeleteModel(
            name='SolicitudVacaciones',
        ),
    ]
