# Generated by Django 5.1 on 2024-11-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0024_solicitudvacaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
