# Generated by Django 5.1 on 2024-11-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0026_alter_solicitud_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('vacaciones', 'Días de Vacaciones'), ('tramite', 'Permiso Trámite Personal'), ('administrativo', 'Día Administrativo'), ('cumpleanos', 'Descanso por Cumpleaños'), ('cumpleanos_hijo', 'Descanso por Cumpleaños Hijo/a'), ('otra', 'Otra')], max_length=50),
        ),
        migrations.DeleteModel(
            name='SolicitudVacaciones',
        ),
    ]
