# Generated by Django 5.1 on 2024-11-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0027_alter_solicitud_tipo_delete_solicitudvacaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('tramite', 'Permiso Trámite Personal'), ('administrativo', 'Día Administrativo'), ('cumpleanos', 'Descanso por Cumpleaños'), ('cumpleanos_hijo', 'Descanso por Cumpleaños Hijo/a'), ('otra', 'Otra')], max_length=50),
        ),
    ]
