# Generated by Django 5.1.3 on 2024-12-01 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0029_solicitudvacaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoDescargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=255)),
                ('fecha_descarga', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_descargados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
