# Generated by Django 5.1 on 2024-08-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0004_alter_customuser_salud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='edad',
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
