# Generated by Django 5.1 on 2024-08-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0005_remove_customuser_edad_customuser_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargafamiliar',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
