# Generated by Django 5.1 on 2024-08-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0009_beneficio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficio',
            old_name='nombre',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='beneficio',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='beneficios/'),
        ),
    ]
