# Generated by Django 5.1 on 2024-08-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0011_comentario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='afp',
            field=models.CharField(blank=True, choices=[('capital', 'AFP Capital'), ('cuprum', 'AFP Cuprum'), ('habitat', 'AFP Habitat'), ('modelo', 'AFP Modelo'), ('planvital', 'AFP Planvital'), ('provida', 'AFP Provida'), ('uno', 'AFP Uno')], max_length=30, null=True),
        ),
    ]
