# Generated by Django 5.1 on 2024-08-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0003_customuser_direccion_customuser_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='salud',
            field=models.CharField(blank=True, choices=[('fonasa', 'Fonasa'), ('banmedica', 'Banmédica'), ('colmena', 'Colmena Golden Cross'), ('consalud', 'Consalud'), ('cruzblanca', 'CruzBlanca'), ('esencial', 'Esencial'), ('masvida', 'Nueva Masvida'), ('vidatres', 'Vida Tres')], max_length=30, null=True),
        ),
    ]
