# Generated by Django 5.1 on 2024-08-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0006_alter_cargafamiliar_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='participantes',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='modulo',
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Evaluacion',
        ),
        migrations.DeleteModel(
            name='Modulo',
        ),
    ]
