# Generated by Django 5.1 on 2024-10-15 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiones', '0014_denuncia'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='gestiones.denuncia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
